// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymSOTHUgCZx562UCma4gRqM3OFscdzAg',
    appId: '1:283553854639:web:de91752c79680fec11d05a',
    messagingSenderId: '283553854639',
    projectId: 'first-app-7d6b7',
    authDomain: 'first-app-7d6b7.firebaseapp.com',
    databaseURL: 'https://first-app-7d6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-7d6b7.appspot.com',
    measurementId: 'G-7F6RDCX2G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1E9PyXB2iwIE1PswwSZsSvDueF5ozUo',
    appId: '1:283553854639:android:b38dafd22550f13911d05a',
    messagingSenderId: '283553854639',
    projectId: 'first-app-7d6b7',
    databaseURL: 'https://first-app-7d6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-7d6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIjaJM2EovlYVvt4Ez0bkA6jokhST51CM',
    appId: '1:283553854639:ios:2453fac84c99035611d05a',
    messagingSenderId: '283553854639',
    projectId: 'first-app-7d6b7',
    databaseURL: 'https://first-app-7d6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-7d6b7.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIjaJM2EovlYVvt4Ez0bkA6jokhST51CM',
    appId: '1:283553854639:ios:23d567fa84bfa32a11d05a',
    messagingSenderId: '283553854639',
    projectId: 'first-app-7d6b7',
    databaseURL: 'https://first-app-7d6b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-7d6b7.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
